name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing on ubuntu-latest and Node LTS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-lts-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-lts-yarn-
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-lts-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-lts-jest-
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test:ci --logHeapUsage
        env:
          CI: true
      - name: Report Coverage
        run: yarn coverage
