name: Release
on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  release:
    name: '/'
    uses: technology-studio/github-workflows/.github/workflows/_release.yml@main
    secrets: inherit
